name: Earth Bot

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日00時00分（UTC）に実行
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Earth image link from NASA EPIC API
        run: |
          image_date=$(date -u +%Y-%m-%d)
          
          response=$(curl -s "https://epic.gsfc.nasa.gov/api/natural/date/$image_date")
          image_name=$(echo $response | jq -r '.[0].image')

          image_url="https://epic.gsfc.nasa.gov/archive/natural/$(date -u +%Y/%m/%d)/png/${image_name}.png"

          echo "# Earth Release v$(date +'%Y.%m.%d')" > release-notes.md
          echo "![Earth Image](${image_url})" >> release-notes.md
          echo "" >> release-notes.md
          echo "Today, the universe has released another day with version $(date +'%Y.%m.%d')." >> release-notes.md
          echo "- Image captured by NASA's DSCOVR satellite." >> release-notes.md
          echo "- Enjoy your day!" >> release-notes.md

      - name: Commit changes
        run: |
          git config --local user.name "Daily Earth Bot"
          git config --local user.email "earth-bot@example.com"
          git add release-notes.md
          git commit -m "Earth Release v$(date +'%Y.%m.%d')" || echo "Nothing to commit"

      - name: Push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://horiyu:${GH_PAT}@github.com/horiyu/earth-bot.git
          git push
